---
name: DevSecOps Pipeline

on:
  push:
    branches: ["main"]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3

      - name: Scan dependencies (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: table
          exit-code: "0"

      - name: Scan Docker image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp
          format: table
          exit-code: "0"
      - name: Run Conftest
        uses: instrumenta/conftest-action@master
        with:
          files: deployment.yaml
